### ISSUE TITLE
Implementation of a query builder to improve the power

### ISSUE THREAD

**Issue by endersoncosta** [herbsjs/herbs2knex#8]
I believe that we need to implement a powerful query builder to increase the possibilities, like the `knex`.

A tool like this provides a bridge to any database, without increase too much the time expended in the adaptations...

In addition to other facilities, like Seeds and Migrations...

**Comment by dalssoft** [comment]
I don't mind changing the driver for a more abstract layer such as knex and making this lib more generic.

We just need to change the name of the lib if this happens: herbs2db? herbs2knex looks more appropriate since the project using this lib should pass a knex instance (with db config, etc) so knex is something we cannot abstract in the name

> In addition to other facilities, like Seeds and Migrations...

I don't see how seed and migration should be part of this lib. How Herbs could help here?

**Comment by endersoncosta** [comment]
About seed I'm too don't see in this moment, maybe in the future, but we can generate the first migration based in the entity, leaving only maintenance and customization to the dev. This would bring a gain at the beginning of the project.

**Comment by endersoncosta** [comment]
about the name **`herbs2knex`** isn't a problem, but it's not an easy name to devs that don't know about the knex, maybe **`herbs2db`** or **`herbsDbConnector`** could be more intuitive, even without giving the full idea in the name...

**Comment by m7vicente** [comment]
herbs2db is a really good name, but, the lib is really using just `got`, another possibility would be call gotu2repository or gotu2db.

**Comment by dalssoft** [comment]
I'm closing this issue since it seems to be old and not updated.
